apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: dumlong-ingress
    namespace: {{.Values.namespace}}
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
    rules:
        - host: {{.Values.ingress.host }}
          http:
              paths:
                  - backend:
                        serviceName: dumlong-svc
                        servicePort: 80
                    path: {{.Values.ingress.path }}
    tls:
        - hosts:
              - {{.Values.ingress.host }}
          secretName: {{.Values.ingress.secret }}
